language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: jKBn/1FV9xoORPEgdwofJkTYp5bNvX+3rkpvL3Cahm1MzLskO4+LXgWM1HFBvM32XssRzYZ/qSBq1zmfajKomIq9juXbYAFk0DY/1YnoqhqUjzl5Mz57LhNcUHN0x7xJOUxs9MioPy1rmTG6U+MOJN7itSMILhf+xMayh6DmBcDdGxXGHFrLKIbB38bNfSdwaKzdLfp+kB3SrK6q9NcyuDD8VLv3UUZMK8rr5ZWQfW987VWGeYwMjDebVBWYl0F0Hk0ffmPOWR/ChVu6m4UCgm8ag4E9hRoAu0kgJ84/aSnQeFqAa7rE7dlkc4JXMkbL9988iWvK62qgnRSfefzMx6QT82KWQUCV8o25VYiSguwK511H79vF6yZfV6eLjEE6G5Mp3LNy2Cu2dFsJS2T3vt473rpv1oGaS+F/GEjQtzCjt+rRu3ypZqiSVJUAwLPBTfN7Nunc7456EW3iZnVtN7jamvqu9PBS/t32btM58bhaUZ5FmBlmxmqtuOvL/OeRXaUL1X6Qn4c0V4u47Vbq0K9OrpgrExXMfX8VF9VN6co3GV01XIDkQnJCB7cTTeANRHiE3IHqdJgGWTIGuF3bblbExRrjdjP2YBj+fmi4DTAiOgzB2AwuxcMvCjsWl/WElYNi0jBQpbwlMcIzXHoB4JjIr6FtUNi1zBqTYCgOo/0=
  app: vast-cliffs-24756
  on:
    repo: nfcortega89/airtime1
